default: &default
  LOG_LEVEL: "info"
  PORT: 8080
  JWT_SECRET: "my_secret"
  MAIL_API_KEY: c22e9891bcc32334d85d77fb9cf9cd8a
  DB_HOST: localhost
  DB_NAME: app
  DB_USER: root
  DB_PASSWORD: root
  DB_PORT: 5432
  DB_TYPE: postgres
  DB_MAX_IDLE_CONNS: 10
  DB_MAX_OPEN_CONNS: 0
  DB_MAX_LIFE_TIME: 1m
  DB_MAX_IDLE_TIME: 10m

development:
  <<: *default

stg:
  <<: [*default]

prd:
  <<: [*default]
  LGO_LEVEL: "debug"

test:
  <<: *default
