default: &default
  LOG_LEVEL: "info"
  PORT: 3000
  DB_HOST: localhost
  DB_NAME: app
  DB_USER: luda
  DB_PASSWORD: luda
  DB_PORT: 5432
  DB_TYPE: postgres
  DB_MAX_IDLE_CONNS: 10
  DB_MAX_OPEN_CONNS: 0
  DB_MAX_LIFE_TIME: 1m
  DB_MAX_IDLE_TIME: 10m

development:
  <<: *default

stg:
  <<: [*default]

prd:
  <<: [*default]

test:
  <<: *default