default: &default
  LOG_LEVEL: "info"
  PORT: 3000
  DB_TYPE: postgres
  DB_MAX_IDLE_CONNS: 10
  DB_MAX_OPEN_CONNS: 0
  DB_MAX_LIFE_TIME: 1m
  DB_MAX_IDLE_TIME: 10m

development:
  <<: *default
  DB_HOST: localhost
  DB_NAME: app
  DB_USER: root
  DB_PASSWORD: root
  DB_PORT: 5432

stg:
  <<: [*default]

prd:
  <<: [*default]

test:
  <<: *default